<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="52" started-at="2012-03-13T09:57:06Z" finished-at="2012-03-13T09:57:06Z">
    <groups>
      <group name="P1">
        <method signature="Module1Test.TC00002()[pri:0, instance:Module1Test@6581ed9e]" name="TC00002" class="Module1Test"/>
      </group> <!-- P1 -->
      <group name="BVT">
        <method signature="Module1Test.TC00001()[pri:0, instance:Module1Test@6581ed9e]" name="TC00001" class="Module1Test"/>
        <method signature="Module1Test.TC00003()[pri:0, instance:Module1Test@6581ed9e]" name="TC00003" class="Module1Test"/>
      </group> <!-- BVT -->
      <group name="P0">
        <method signature="Module1Test.TC00001()[pri:0, instance:Module1Test@6581ed9e]" name="TC00001" class="Module1Test"/>
      </group> <!-- P0 -->
      <group name="P2">
        <method signature="Module1Test.TC00003()[pri:0, instance:Module1Test@6581ed9e]" name="TC00003" class="Module1Test"/>
      </group> <!-- P2 -->
      <group name="FVT">
        <method signature="Module1Test.TC00002()[pri:0, instance:Module1Test@6581ed9e]" name="TC00002" class="Module1Test"/>
      </group> <!-- FVT -->
    </groups>
    <test name="Command line test" duration-ms="52" started-at="2012-03-13T09:57:06Z" finished-at="2012-03-13T09:57:06Z">
      <class name="Module1Test">
        <test-method status="PASS" signature="TC00001()[pri:0, instance:Module1Test@6581ed9e]" name="TC00001" duration-ms="14" started-at="2012-03-13T09:57:06Z" description="this is test1 description" finished-at="2012-03-13T09:57:06Z">
        </test-method> <!-- TC00001 -->
        <test-method status="FAIL" signature="TC00002()[pri:0, instance:Module1Test@6581ed9e]" name="TC00002" duration-ms="1" started-at="2012-03-13T09:57:06Z" description="this is test2 description" finished-at="2012-03-13T09:57:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<1> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<1> but was:<2>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
	at Module1Test.TC00002(Module1Test.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- TC00002 -->
        <test-method status="PASS" signature="TC00003()[pri:0, instance:Module1Test@6581ed9e]" name="TC00003" duration-ms="1" started-at="2012-03-13T09:57:06Z" description="this is test3 description" finished-at="2012-03-13T09:57:06Z">
        </test-method> <!-- TC00003 -->
      </class> <!-- Module1Test -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
